# Generated by Django 5.0.2 on 2024-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='tickets',
            name='uid',
            field=models.CharField(max_length=100, verbose_name='Ticket unique number'),
        ),
    ]
