# Generated by Django 5.0.2 on 2024-03-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_partner_voucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Patrners'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
    ]
