# Generated by Django 5.0.2 on 2024-03-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_partner_options_alter_voucher_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='for_partner',
            new_name='partner',
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Partner name'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Ticket unique number')),
                ('vouchers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.partner')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AlterField(
            model_name='voucher',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_vouchers', to='tickets.ticket'),
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
