# Generated by Django 5.0.2 on 2024-03-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_for_partner_voucher_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vouchers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.partner', verbose_name='Vouchers'),
        ),
    ]
