# Generated by Django 5.0.2 on 2024-03-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_voucher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='vouchers',
        ),
    ]
