# Generated by Django 5.0.2 on 2024-03-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used')], default='active', max_length=20),
        ),
    ]
