# Generated by Django 5.0.2 on 2024-03-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_partner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='holder',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ticket holder name'),
        ),
    ]
