# Generated by Django 5.0.2 on 2024-03-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.partner', verbose_name='Partner'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tickets.ticket')),
                ('vouchers', models.ManyToManyField(blank=True, to='tickets.voucher')),
            ],
        ),
    ]
