# Generated by Django 5.0.2 on 2024-03-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.package', verbose_name='Package'),
        ),
    ]
