# Generated by Django 5.0.2 on 2024-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_voucher_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='vouchers',
        ),
        migrations.AddField(
            model_name='package',
            name='partners',
            field=models.ManyToManyField(to='tickets.partner'),
        ),
    ]
