# Generated by Django 5.0.2 on 2024-03-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Ticket number'),
        ),
    ]
