# Generated by Django 5.0.2 on 2024-03-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticket_qr_link_alter_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_image'),
        ),
    ]
