# Generated by Django 5.0.2 on 2024-03-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
    ]
