# Generated by Django 5.0.2 on 2024-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_remove_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_images'),
        ),
    ]
