# Generated by Django 5.0.2 on 2024-03-08 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_remove_package_partners_remove_voucher_partner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='package',
            name='facilitators',
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Partner name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner_images')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Patrners',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='partners',
            field=models.ManyToManyField(to='tickets.partner'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='vouchers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.partner', verbose_name='Vouchers'),
        ),
        migrations.DeleteModel(
            name='Facilitators',
        ),
    ]
