# Generated by Django 5.0.2 on 2024-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_remove_voucher_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='facilitator',
            field=models.BooleanField(default=False, verbose_name='Is facilitator'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='activities',
            field=models.BooleanField(default=False, verbose_name='Is activities'),
        ),
    ]
