# Generated by Django 5.0.2 on 2024-03-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_partner_facilitator_voucher_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='activities',
        ),
    ]
