# Generated by Django 5.0.2 on 2024-03-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_remove_voucher_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not paid', 'Not paid')], default='Not paid', max_length=20),
        ),
    ]
