# Generated by Django 5.0.2 on 2024-03-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_ticket_payment_method_ticket_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='post_discount',
            field=models.BooleanField(default=False),
        ),
    ]
