# Generated by Django 5.0.2 on 2024-04-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_tickettemplate'),
        ('tickets', '0032_ticket_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticket_templates', verbose_name='Ticket template')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_template', to='events.event')),
            ],
        ),
    ]
