# Generated by Django 5.0.2 on 2024-04-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_ticket_template_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketTemplate',
        ),
    ]
