# Generated by Django 5.0.2 on 2024-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_date_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Organizer info'),
        ),
    ]
