# Generated by Django 5.0.2 on 2024-04-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_organizer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='description',
            new_name='info',
        ),
    ]
