# Generated by Django 5.0.2 on 2024-04-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_description_organizer_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimages',
            options={'verbose_name': 'Events Images', 'verbose_name_plural': 'Events Images'},
        ),
    ]
