# Generated by Django 5.0.2 on 2024-04-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimages',
            options={'verbose_name': 'Event Images', 'verbose_name_plural': 'Event Images'},
        ),
    ]
