# Generated by Django 5.0.2 on 2024-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
    ]
