# Generated by Django 5.0.2 on 2024-05-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimages',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Image caption'),
        ),
    ]
